import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Hero from "@/components/hero/Hero";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <Navbar />
        <div className="containers">
          <div className="flex gap-x-3 mt-4">
            <div className=" w-[804px] ">{children}</div>
            <div className="h-full w-[326px] ">
              <Hero />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
